GRANT SELECT ON DBA_DATA_FILES TO ousmane;
GRANT SELECT ON DBA_USERS TO OUSMANE;
GRANT SELECT ON V_$SQL TO OUSMANE;
GRANT SELECT ON V_$SESSION TO ousmane;
GRANT SELECT ON V_$SYSMETRIC TO ousmane;
GRANT SELECT_CATALOG_ROLE TO ousmane;
GRANT SELECT ON V_$SYSMETRIC TO ousmane;
GRANT SELECT ANY DICTIONARY TO ousmane;
ALTER USER ousmane ACCOUNT UNLOCK;
/*GRANT EXECUTE ON nom_de_la_procedure TO nom_de_l_utilisateur;  */
 